#ifndef PRODUCT_CONFIG_H
#define PRODUCT_CONFIG_H

#define PRODUCT_ID_STRING             "bluepill_f103c8"
#define PRODUCT_DISPLAY_NAME          "BluePill STM32F103C8T6"
#define PRODUCT_HSE_VALUE_HZ          8000000U
#define PRODUCT_SYSCLK_HZ             72000000U
#define PRODUCT_FLASH_BYTES           65536U
#define PRODUCT_RAM_BYTES             20480U

#define PRODUCT_LED0_GPIO_PORT        GPIOC
#define PRODUCT_LED0_GPIO_CLOCK()     __HAL_RCC_GPIOC_CLK_ENABLE()
#define PRODUCT_LED0_PIN              GPIO_PIN_13
#define PRODUCT_LED0_ACTIVE_STATE     GPIO_PIN_RESET
#define PRODUCT_LED0_INACTIVE_STATE   GPIO_PIN_SET
#define PRODUCT_LED0_GPIO_SPEED       GPIO_SPEED_FREQ_LOW

#define PRODUCT_HAS_KEY0              0

#define PRODUCT_CONSOLE_GPIO_PORT     GPIOA
#define PRODUCT_CONSOLE_GPIO_CLOCK()  __HAL_RCC_GPIOA_CLK_ENABLE()
#define PRODUCT_CONSOLE_UART_CLOCK()  __HAL_RCC_USART1_CLK_ENABLE()
#define PRODUCT_CONSOLE_UART          USART1
#define PRODUCT_CONSOLE_NAME_STRING   "USART1"
#define PRODUCT_CONSOLE_TX_STRING     "PA9"
#define PRODUCT_CONSOLE_RX_STRING     "PA10"
#define PRODUCT_CONSOLE_TX_PIN        GPIO_PIN_9
#define PRODUCT_CONSOLE_RX_PIN        GPIO_PIN_10

#endif
