# ==============================================================================
# RT-Thread Makefile
# ==============================================================================

TOPDIR ?= ../../..
include $(TOPDIR)/Make.defs
include Make.defs

OBJS = $(addprefix $(BUILD_DIR)/, $(CSRCS:.c=.o))

all: $(OBJS)

.PHONY: all
