#!/usr/bin/env python3
"""
menuconfig.py - Cross-platform Kconfig menuconfig and header generator for STM32F103
"""

import sys
import os
import subprocess

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
PROJECT_ROOT = os.path.dirname(SCRIPT_DIR)
KCONFIG_PATH = os.path.join(PROJECT_ROOT, "Kconfig")
DOTCONFIG_PATH = os.path.join(PROJECT_ROOT, ".config")
GEN_DIR = os.path.join(PROJECT_ROOT, "build", "generated")
AUTOCONF_H_PATH = os.path.join(GEN_DIR, "autoconf.h")
CMAKE_CONFIG_PATH = os.path.join(PROJECT_ROOT, "cmake", "kconfig.cmake")

def ensure_dependencies(gui=False):
    try:
        import kconfiglib
        if gui:
            import guiconfig
        else:
            import menuconfig
    except ImportError:
        print(">> [INFO] kconfiglib or curses is not installed in current Python environment.")
        print(">> [INFO] Installing kconfiglib...")
        packages = ["kconfiglib"]
        if os.name == 'nt' and not gui:
            packages.append("windows-curses")
        subprocess.check_call([sys.executable, "-m", "pip", "install"] + packages)

def generate_headers_and_cmake(kconf):
    os.makedirs(GEN_DIR, exist_ok=True)
    os.makedirs(os.path.dirname(CMAKE_CONFIG_PATH), exist_ok=True)

    # 1. Generate autoconf.h
    kconf.write_autoconf(AUTOCONF_H_PATH)
    print(f">> Generated C Header: {AUTOCONF_H_PATH}")

    # 2. Generate cmake/kconfig.cmake
    with open(CMAKE_CONFIG_PATH, "w", encoding="utf-8") as f:
        f.write("# Automatically generated by menuconfig.py. DO NOT EDIT.\n\n")
        for sym in kconf.unique_defined_syms:
            if sym.str_value == "y":
                f.write(f'set({sym.name} ON CACHE INTERNAL "Kconfig option")\n')
                f.write(f'add_compile_definitions({sym.name}=1)\n')
            elif sym.str_value == "n":
                f.write(f'set({sym.name} OFF CACHE INTERNAL "Kconfig option")\n')
            else:
                val = sym.str_value
                if sym.type in (kconfiglib.INT, kconfiglib.HEX):
                    f.write(f'set({sym.name} {val} CACHE INTERNAL "Kconfig option")\n')
                    f.write(f'add_compile_definitions({sym.name}={val})\n')
                elif sym.type == kconfiglib.STRING:
                    f.write(f'set({sym.name} "{val}" CACHE INTERNAL "Kconfig option")\n')
                    f.write(f'add_compile_definitions({sym.name}="{val}")\n')

    print(f">> Generated CMake Config: {CMAKE_CONFIG_PATH}")

def main():
    os.chdir(PROJECT_ROOT)
    gui_mode = "--gui" in sys.argv

    ensure_dependencies(gui=gui_mode)
    import kconfiglib

    # Set default KCONFIG_CONFIG environment
    os.environ["KCONFIG_CONFIG"] = DOTCONFIG_PATH

    kconf = kconfiglib.Kconfig(KCONFIG_PATH)

    if os.path.exists(DOTCONFIG_PATH):
        kconf.load_config(DOTCONFIG_PATH)

    if gui_mode:
        import guiconfig
        guiconfig.menuconfig(kconf)
    else:
        import menuconfig
        menuconfig.menuconfig(kconf)

    # Write .config
    kconf.write_config(DOTCONFIG_PATH)
    print(f">> Saved configuration to {DOTCONFIG_PATH}")

    # Generate autoconf.h and cmake/kconfig.cmake
    generate_headers_and_cmake(kconf)

if __name__ == "__main__":
    main()
