# Automatically generated by menuconfig. DO NOT EDIT.

# Target Chip
set(CONFIG_CHIP_STM32F103CB ON CACHE INTERNAL "Kconfig option")
add_compile_definitions(CONFIG_CHIP_STM32F103CB=1)
set(CONFIG_ARCH_ARM_CORTEX_M3 ON CACHE INTERNAL "Kconfig option")
add_compile_definitions(CONFIG_ARCH_ARM_CORTEX_M3=1)

set(CONFIG_SYS_CLOCK_FREQ_HZ 72000000 CACHE INTERNAL "Kconfig option")
add_compile_definitions(CONFIG_SYS_CLOCK_FREQ_HZ=72000000)

set(CONFIG_HSE_VALUE_HZ 8000000 CACHE INTERNAL "Kconfig option")
add_compile_definitions(CONFIG_HSE_VALUE_HZ=8000000)

# RTOS
set(CONFIG_RTOS_NONE ON CACHE INTERNAL "Kconfig option")
add_compile_definitions(CONFIG_RTOS_NONE=1)

# Application
set(CONFIG_APP_ENABLE_HEARTBEAT ON CACHE INTERNAL "Kconfig option")
add_compile_definitions(CONFIG_APP_ENABLE_HEARTBEAT=1)
set(CONFIG_APP_LED_BLINK_INTERVAL_MS 500 CACHE INTERNAL "Kconfig option")
add_compile_definitions(CONFIG_APP_LED_BLINK_INTERVAL_MS=500)
set(CONFIG_APP_ENABLE_BUTTON_TASK ON CACHE INTERNAL "Kconfig option")
add_compile_definitions(CONFIG_APP_ENABLE_BUTTON_TASK=1)

# BSP
set(CONFIG_BSP_USING_LED ON CACHE INTERNAL "Kconfig option")
add_compile_definitions(CONFIG_BSP_USING_LED=1)
set(CONFIG_BSP_USING_KEY ON CACHE INTERNAL "Kconfig option")
add_compile_definitions(CONFIG_BSP_USING_KEY=1)
set(CONFIG_BSP_USING_USART1 ON CACHE INTERNAL "Kconfig option")
add_compile_definitions(CONFIG_BSP_USING_USART1=1)
set(CONFIG_BSP_USART1_BAUDRATE 115200 CACHE INTERNAL "Kconfig option")
add_compile_definitions(CONFIG_BSP_USART1_BAUDRATE=115200)

# Drivers
set(CONFIG_DRIVER_USE_HAL ON CACHE INTERNAL "Kconfig option")
add_compile_definitions(CONFIG_DRIVER_USE_HAL=1)
set(CONFIG_DRIVER_HAL_GPIO ON CACHE INTERNAL "Kconfig option")
add_compile_definitions(CONFIG_DRIVER_HAL_GPIO=1)
set(CONFIG_DRIVER_HAL_UART ON CACHE INTERNAL "Kconfig option")
add_compile_definitions(CONFIG_DRIVER_HAL_UART=1)
set(CONFIG_DRIVER_HAL_RCC ON CACHE INTERNAL "Kconfig option")
add_compile_definitions(CONFIG_DRIVER_HAL_RCC=1)
