#ifndef PRODUCT_CONFIG_H
#define PRODUCT_CONFIG_H

#define PRODUCT_ID_STRING             "atk_elite_f103ze"
#define PRODUCT_DISPLAY_NAME          "ALIENTEK Elite STM32F103ZET6"
#define PRODUCT_HSE_VALUE_HZ          8000000U
#define PRODUCT_SYSCLK_HZ             72000000U
#define PRODUCT_FLASH_BYTES           524288U
#define PRODUCT_RAM_BYTES             65536U

#define PRODUCT_LED0_GPIO_PORT        GPIOB
#define PRODUCT_LED0_GPIO_CLOCK()     __HAL_RCC_GPIOB_CLK_ENABLE()
#define PRODUCT_LED0_PIN              GPIO_PIN_5
#define PRODUCT_LED0_ACTIVE_STATE     GPIO_PIN_RESET
#define PRODUCT_LED0_INACTIVE_STATE   GPIO_PIN_SET
#define PRODUCT_LED0_GPIO_SPEED       GPIO_SPEED_FREQ_HIGH

#define PRODUCT_LED1_GPIO_PORT        GPIOE
#define PRODUCT_LED1_PIN              GPIO_PIN_5
#define PRODUCT_LED1_ACTIVE_STATE     GPIO_PIN_RESET

#define PRODUCT_HAS_KEY0              1
#define PRODUCT_KEY0_GPIO_PORT        GPIOE
#define PRODUCT_KEY0_GPIO_CLOCK()     __HAL_RCC_GPIOE_CLK_ENABLE()
#define PRODUCT_KEY0_PIN              GPIO_PIN_4
#define PRODUCT_KEY0_PULL             GPIO_PULLUP
#define PRODUCT_KEY0_ACTIVE_STATE     GPIO_PIN_RESET

#define PRODUCT_KEY1_GPIO_PORT        GPIOE
#define PRODUCT_KEY1_PIN              GPIO_PIN_3
#define PRODUCT_KEY1_ACTIVE_STATE     GPIO_PIN_RESET
#define PRODUCT_WAKEUP_GPIO_PORT      GPIOA
#define PRODUCT_WAKEUP_PIN            GPIO_PIN_0
#define PRODUCT_WAKEUP_ACTIVE_STATE   GPIO_PIN_SET

#define PRODUCT_CONSOLE_GPIO_PORT     GPIOA
#define PRODUCT_CONSOLE_GPIO_CLOCK()  __HAL_RCC_GPIOA_CLK_ENABLE()
#define PRODUCT_CONSOLE_UART_CLOCK()  __HAL_RCC_USART1_CLK_ENABLE()
#define PRODUCT_CONSOLE_UART          USART1
#define PRODUCT_CONSOLE_TX_PIN        GPIO_PIN_9
#define PRODUCT_CONSOLE_RX_PIN        GPIO_PIN_10

#endif
